name: CMake tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure and Build CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build
      
    - name: Install
      run: sudo make -C ${{github.workspace}}/build install
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C -VV

    - name: CPack
      working-directory: ${{github.workspace}}/build
      run: sudo cpack -V
      
    - uses: actions/upload-artifact@v2
      with:
        name: Why-am-I-uploading-this
        path: |
          ${{github.workspace}}/build/*.tar.gz
          ${{github.workspace}}/build/*.sh
