name: CMake tests

on:
  push:
    branches: [ cmake ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure and Build CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build
      
    - name: Install
      run: sudo make -C ${{github.workspace}}/build install
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C -VV
      
