name: CMake tests

on:
  push:
    branches: [ cmake ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -C ${{github.workspace}}/build 
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build 
    
    - name: Install
      run: sudo make -C ${{github.workspace}}/ install
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C -VV
      
